root: true
plugins:
  - node
extends:
  - standard
  - plugin:node/recommended
rules:
  comma-dangle: 0
  max-lines:
    - error
    - 200
  valid-jsdoc:
    - error
    - matchDescription: ".+"
      requireParamDescription: false
      requireReturnDescription: false
env:
  node: true
  browser: false
